import { useState, useRef, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Sparkles, Terminal, Copy, Check, Sliders, Box, Layers, RefreshCw, Download, ArrowRight } from 'lucide-react';

const PRESETS = [
  {
    id: 'facade',
    name: 'Parametric Kinetic Facade',
    software: 'Revit (.RFA / Dynamo)',
    prompt: 'Parametric kinetic louvered solar screen for commercial tower, responsive to azimuth sun angles between 15° and 75°, nested family with aluminum mullions and double-glazed low-E insulated glass.',
    codeType: 'python',
    code: `# Autodesk Revit - Dynamo Python Script
# Generated by ARCHVIBE AI Generative Engine
import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
trans = Transaction(doc, 'Generate Parametric Louvers')
trans.Start()

# Parameters: Bay spacing = 1500mm, Louver rotation = 42.5 deg
bay_count = 12
height_levels = 8
for i in range(bay_count):
    for j in range(height_levels):
        origin = XYZ(i * 1.5, 0, j * 3.8)
        # Create Adaptive BIM Family Instance
        panel = doc.Create.NewFamilyInstance(origin, louver_symbol, StructuralType.NonStructural)
        panel.LookupParameter('Angle_Azimuth').Set(42.5 + (i * 2.2))
        panel.LookupParameter('Louver_Material').Set('Anodized Champagne Bronze')

trans.Commit()
OUT = f'Successfully instantiated {bay_count * height_levels} parametric louver units.'`,
    blueprint: {
      type: 'facade',
      width: 600,
      height: 320,
      elements: 14
    }
  },
  {
    id: 'floorplan',
    name: 'AutoCAD Dynamic Office Layout',
    software: 'AutoCAD (.DWG / AutoLISP)',
    prompt: 'Autonomous corporate office floor layout, 4-bay structural grid at 8.4m column intervals, dual central elevator core, perimeter curtain wall glazing, automated AIA layer assignment.',
    codeType: 'lisp',
    code: `; ARCHVIBE AutoLISP Generative Generator
; Automated Structural Grid & Core Layout
(defun c:ARCH_OFFICE_GEN ( / pt0 grid_x grid_y col_size)
  (setvar "CMDECHO" 0)
  (command "-LAYER" "M" "S-GRID" "C" "1" "" "")
  (command "-LAYER" "M" "A-WALL-CORE" "C" "4" "" "")
  (command "-LAYER" "M" "A-GLAZ-CURT" "C" "3" "" "")
  
  (setq pt0 '(0.0 0.0 0.0))
  ; Draw 8.4m modular grid system
  (repeat 6
    (command "LINE" (list (* i 8400.0) 0.0) (list (* i 8400.0) 33600.0) "")
    (command "TEXT" (list (* i 8400.0) -1200.0) 450.0 0 (chr (+ 65 i)))
  )
  ; Generate Reinforced Core Void
  (command "RECTANG" '(12600.0 10500.0) '(21000.0 23100.0))
  (princ "\\nAutoCAD: Parametric Office Floor Grid Generated on Layer S-GRID.")
  (princ)
)`,
    blueprint: {
      type: 'floorplan',
      width: 600,
      height: 320,
      elements: 8
    }
  },
  {
    id: 'midjourney',
    name: 'Master AI Render Matrix',
    software: 'Midjourney v6.1 & ControlNet',
    prompt: 'Futuristic timber-and-glass research pavilion, organic curved glu-lam beams, daylight filtered through perforated kinetic brass ceiling, architectural photography, Hasselblad H6D-100c, 8k resolution, architectural section perspective --ar 16:9 --style raw --v 6.1',
    codeType: 'prompt',
    code: `// Prompt Matrix for Architecture AI Renders:
/imagine prompt: Ultra-modern civic cultural center with parametrically undulating mass-timber roof structure, biophilic interior courtyard with ficus trees, floor-to-ceiling ultra-clear structural glazing with low iron content, warm recessed 3000K LED linears, overcast Copenhagen afternoon lighting, hyper-detailed architectural section perspective, architectural model photograph by Iwan Baan and Hufton+Crow, 8k render, photorealistic physical textures, ISO 100, 35mm architectural lens, f/8 --ar 16:9 --style raw --v 6.1 --s 250

// ControlNet Depth & Canny Guidance:
Preprocessor: canny_edge_detector | Model: control_v11p_sd15_canny
Conditioning: DWG_Wireframe_Level01.png (Weight: 1.25, Guidance End: 0.85)`,
    blueprint: {
      type: 'canopy',
      width: 600,
      height: 320,
      elements: 16
    }
  },
  {
    id: 'truss',
    name: 'Parametric Steel Space-Frame',
    software: 'Rhino / Grasshopper / Revit',
    prompt: 'Double-curvature diagrid stadium canopy, spherical node connectors with cast steel pins, automated dead load calculation and camber curvature calculation.',
    codeType: 'python',
    code: `# Grasshopper & Revit DirectShape Integration
import rhinoscriptsyntax as rs
import math

nodes = []
beams = []
# Generate Parametric Parabolic Vault
span = 60.0
rise = 14.5
for u in range(21):
    for v in range(11):
        x = (u / 20.0 - 0.5) * span
        y = (v / 10.0 - 0.5) * span * 0.6
        z = rise * (1.0 - (2.0 * x / span)**2) * (1.0 - (2.0 * y / (span*0.6))**2)
        nodes.append((x, y, z))

print(f"Computed {len(nodes)} structural space frame coordinates for Revit LOD 400 translation.")`,
    blueprint: {
      type: 'truss',
      width: 600,
      height: 320,
      elements: 22
    }
  }
];

export default function AIPromptGenerator({ onOpenAccessModal }) {
  const [activePreset, setActivePreset] = useState(PRESETS[0]);
  const [customPrompt, setCustomPrompt] = useState(PRESETS[0].prompt);
  const [isGenerating, setIsGenerating] = useState(false);
  const [copied, setCopied] = useState(false);
  const [louverAngle, setLouverAngle] = useState(38);
  const [gridSpacing, setGridSpacing] = useState(12);
  const [showDimensions, setShowDimensions] = useState(true);
  const [showGrid, setShowGrid] = useState(true);
  const [mouseCoord, setMouseCoord] = useState({ x: 0, y: 0 });

  const handlePresetSelect = (preset) => {
    setActivePreset(preset);
    setCustomPrompt(preset.prompt);
  };

  const handleGenerate = () => {
    setIsGenerating(true);
    setTimeout(() => {
      setIsGenerating(false);
    }, 600);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(activePreset.code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleCanvasMouseMove = (e) => {
    const rect = e.currentTarget.getBoundingClientRect();
    const x = Math.round((e.clientX - rect.left) * 10);
    const y = Math.round((e.clientY - rect.top) * 10);
    setMouseCoord({ x, y });
  };

  return (
    <section id="ai-generator" className="relative py-28 bg-ink-950 border-t border-white/10 overflow-hidden">
      {/* Background blueprint grid */}
      <div className="absolute inset-0 bg-[linear-gradient(to_right,rgba(232,255,71,0.03)_1px,transparent_1px),linear-gradient(to_bottom,rgba(232,255,71,0.03)_1px,transparent_1px)] bg-[size:40px_40px] pointer-events-none" />

      <div className="relative max-w-7xl mx-auto px-6 md:px-12">
        {/* Section Heading */}
        <div className="flex flex-col md:flex-row md:items-end justify-between mb-16 gap-6">
          <div>
            <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-signal/10 border border-signal/30 text-signal font-mono text-xs uppercase tracking-wider mb-4">
              <Sparkles size={14} className="animate-spin-slow" />
              Live Interactive Architecture Engine
            </div>
            <h2 className="font-display text-4xl sm:text-5xl md:text-6xl text-white font-bold tracking-tight">
              AI Prompt to <span className="text-signal">Parametric CAD</span>
            </h2>
            <p className="font-body text-mist-900 text-lg max-w-2xl mt-4">
              Type natural architectural concepts or pick a preset. Our generative engine translates your spatial intent directly into production-ready AutoLISP, Revit Dynamo scripts, and parametric blueprints.
            </p>
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={onOpenAccessModal}
              className="bg-signal text-ink-950 font-display font-semibold px-6 py-3 rounded-full hover:bg-signal-dim transition-all flex items-center gap-2 shadow-[0_0_25px_rgba(232,255,71,0.25)]"
            >
              <span>Unlock 1000 Free Pass</span>
              <ArrowRight size={16} />
            </button>
          </div>
        </div>

        {/* Preset Selector Chips */}
        <div className="flex flex-wrap gap-2.5 mb-8">
          {PRESETS.map((p) => {
            const isActive = activePreset.id === p.id;
            return (
              <button
                key={p.id}
                onClick={() => handlePresetSelect(p)}
                className={`px-4 py-2.5 rounded-xl font-mono text-xs transition-all flex items-center gap-2 border ${
                  isActive
                    ? 'bg-signal text-ink-950 border-signal font-bold shadow-lg shadow-signal/20'
                    : 'bg-ink-900/90 text-mist-700 border-white/10 hover:border-signal/50 hover:text-white'
                }`}
              >
                <Box size={14} />
                <span>{p.name}</span>
                <span className={`text-[10px] px-1.5 py-0.5 rounded ${isActive ? 'bg-ink-950/20 text-ink-950' : 'bg-ink-800 text-mist-900'}`}>
                  {p.software.split(' ')[0]}
                </span>
              </button>
            );
          })}
        </div>

        {/* Studio Grid: Left Input & Code, Right Live Blueprint Canvas */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          
          {/* Left Column: Prompt Editor & Generated Script */}
          <div className="lg:col-span-6 flex flex-col gap-6">
            {/* Prompt Input Box */}
            <div className="bg-ink-900/80 border border-white/10 rounded-2xl p-6 backdrop-blur-md relative">
              <div className="flex items-center justify-between mb-3">
                <span className="font-mono text-xs uppercase tracking-wider text-mist-900 flex items-center gap-2">
                  <Terminal size={14} className="text-signal" />
                  Architectural Intent / Prompt
                </span>
                <span className="font-mono text-[11px] text-signal bg-signal/10 px-2 py-0.5 rounded">
                  Target: {activePreset.software}
                </span>
              </div>

              <textarea
                value={customPrompt}
                onChange={(e) => setCustomPrompt(e.target.value)}
                rows={3}
                className="w-full bg-ink-950/90 border border-white/10 rounded-xl p-4 text-white font-mono text-xs sm:text-sm focus:outline-none focus:border-signal/70 transition-colors resize-none selection:bg-signal selection:text-ink-950"
                placeholder="Describe your facade, floor plan, or parametric BIM family..."
              />

              <div className="flex items-center justify-between mt-4">
                <div className="text-[11px] font-mono text-mist-900">
                  {customPrompt.length} characters &bull; LOD 400 Model
                </div>
                <button
                  onClick={handleGenerate}
                  disabled={isGenerating}
                  className="bg-ink-800 hover:bg-signal hover:text-ink-950 text-white border border-white/15 px-4 py-2 rounded-xl text-xs font-mono font-medium transition-all flex items-center gap-2"
                >
                  <RefreshCw size={13} className={isGenerating ? 'animate-spin' : ''} />
                  <span>{isGenerating ? 'Synthesizing...' : 'Regenerate Script'}</span>
                </button>
              </div>
            </div>

            {/* Generated Code Output Box */}
            <div className="bg-ink-900/80 border border-white/10 rounded-2xl p-6 backdrop-blur-md flex-1 flex flex-col">
              <div className="flex items-center justify-between mb-3 border-b border-white/5 pb-3">
                <div className="flex items-center gap-2 font-mono text-xs text-mist-700">
                  <div className="w-2.5 h-2.5 rounded-full bg-red-500/80" />
                  <div className="w-2.5 h-2.5 rounded-full bg-yellow-500/80" />
                  <div className="w-2.5 h-2.5 rounded-full bg-green-500/80" />
                  <span className="ml-2 text-white font-semibold">
                    {activePreset.codeType === 'lisp' ? 'autolisp_routine.lsp' : activePreset.codeType === 'python' ? 'dynamo_revit_script.py' : 'master_render_prompt.txt'}
                  </span>
                </div>
                
                <button
                  onClick={handleCopy}
                  className="flex items-center gap-1.5 text-xs font-mono px-3 py-1.5 rounded-lg bg-ink-800 hover:bg-ink-700 text-mist-100 transition-colors"
                >
                  {copied ? <Check size={14} className="text-green-400" /> : <Copy size={14} />}
                  <span>{copied ? 'Copied!' : 'Copy Code'}</span>
                </button>
              </div>

              <div className="relative flex-1 bg-ink-950/90 rounded-xl p-4 font-mono text-xs overflow-x-auto text-mist-700 leading-relaxed border border-white/5">
                <pre className="text-mist-100">
                  <code>{activePreset.code}</code>
                </pre>
              </div>

              <div className="flex items-center justify-between mt-4 pt-3 border-t border-white/5 text-[11px] font-mono text-mist-900">
                <span>Direct import into AutoCAD 2026 & Revit 2026</span>
                <span className="text-signal flex items-center gap-1">
                  100% Free for 1st 1,000 Users
                </span>
              </div>
            </div>

          </div>

          {/* Right Column: Live Interactive Blueprint Canvas & Parametric Controls */}
          <div className="lg:col-span-6 flex flex-col gap-6">
            <div className="bg-ink-900/80 border border-white/10 rounded-2xl p-6 backdrop-blur-md flex-1 flex flex-col">
              
              {/* Canvas Header */}
              <div className="flex flex-wrap items-center justify-between gap-4 mb-4 pb-3 border-b border-white/5">
                <div className="flex items-center gap-2">
                  <div className="w-2 h-2 rounded-full bg-signal animate-ping" />
                  <span className="font-mono text-xs text-white uppercase tracking-wider font-semibold">
                    Live Vector Blueprint Viewport
                  </span>
                </div>

                {/* Snapping Coordinate HUD */}
                <div className="font-mono text-[11px] bg-ink-950 px-3 py-1 rounded-lg border border-white/10 text-signal flex items-center gap-3">
                  <span>X: {mouseCoord.x || 3420}mm</span>
                  <span className="text-white/20">|</span>
                  <span>Y: {mouseCoord.y || 8140}mm</span>
                  <span className="text-white/20">|</span>
                  <span className="text-mist-700">SNAP: ENDPT</span>
                </div>
              </div>

              {/* Viewport Toggles */}
              <div className="flex items-center gap-4 mb-3 text-xs font-mono text-mist-700">
                <label className="flex items-center gap-1.5 cursor-pointer hover:text-white transition-colors">
                  <input
                    type="checkbox"
                    checked={showGrid}
                    onChange={(e) => setShowGrid(e.target.checked)}
                    className="accent-signal"
                  />
                  <span>Grid (S-GRID)</span>
                </label>
                <label className="flex items-center gap-1.5 cursor-pointer hover:text-white transition-colors">
                  <input
                    type="checkbox"
                    checked={showDimensions}
                    onChange={(e) => setShowDimensions(e.target.checked)}
                    className="accent-signal"
                  />
                  <span>Dimensions (A-DIMS)</span>
                </label>
              </div>

              {/* Interactive Vector Blueprint Canvas */}
              <div
                onMouseMove={handleCanvasMouseMove}
                className="relative flex-1 min-h-[300px] bg-ink-950 rounded-xl border border-white/10 p-4 overflow-hidden flex items-center justify-center cursor-crosshair group"
              >
                {/* Visual coordinate crosshair lines */}
                <div className="absolute inset-0 bg-[radial-gradient(circle_at_center,rgba(232,255,71,0.06)_0,transparent_70%)] pointer-events-none" />
                
                {/* SVG Blueprint graphic */}
                <svg
                  viewBox="0 0 600 320"
                  className="w-full h-full max-h-[320px] transition-all duration-300"
                >
                  <defs>
                    <pattern id="cadGrid" width="20" height="20" patternUnits="userSpaceOnUse">
                      <path d="M 20 0 L 0 0 0 20" fill="none" stroke="rgba(255,255,255,0.04)" strokeWidth="0.5" />
                    </pattern>
                  </defs>

                  {/* Grid background */}
                  {showGrid && <rect width="600" height="320" fill="url(#cadGrid)" />}

                  {/* Render based on active preset */}
                  {activePreset.id === 'facade' && (
                    <g>
                      {/* Floor Slabs */}
                      <line x1="50" y1="60" x2="550" y2="60" stroke="#9898b8" strokeWidth="2" strokeDasharray="4 4" />
                      <line x1="50" y1="160" x2="550" y2="160" stroke="#9898b8" strokeWidth="2" strokeDasharray="4 4" />
                      <line x1="50" y1="260" x2="550" y2="260" stroke="#9898b8" strokeWidth="2" strokeDasharray="4 4" />

                      {/* Mullions and kinetic louvers */}
                      {Array.from({ length: gridSpacing }).map((_, i) => {
                        const x = 70 + i * (460 / (gridSpacing - 1));
                        const angleOffset = Math.sin((i / gridSpacing) * Math.PI) * louverAngle;
                        return (
                          <g key={i}>
                            {/* Vertical Structural Mullion */}
                            <line x1={x} y1="40" x2={x} y2="280" stroke="#e8ff47" strokeWidth="1.5" strokeOpacity="0.4" />
                            {/* Parametric Louvers Tier 1 */}
                            <line
                              x1={x - 14}
                              y1={100 - angleOffset * 0.4}
                              x2={x + 14}
                              y2={100 + angleOffset * 0.4}
                              stroke="#e8ff47"
                              strokeWidth="3"
                              strokeLinecap="round"
                            />
                            {/* Parametric Louvers Tier 2 */}
                            <line
                              x1={x - 14}
                              y1={200 - angleOffset * 0.4}
                              x2={x + 14}
                              y2={200 + angleOffset * 0.4}
                              stroke="#ff6b35"
                              strokeWidth="3"
                              strokeLinecap="round"
                            />
                            {/* Node joints */}
                            <circle cx={x} cy="100" r="3" fill="#ffffff" />
                            <circle cx={x} cy="200" r="3" fill="#ffffff" />
                          </g>
                        );
                      })}

                      {/* Dimension lines */}
                      {showDimensions && (
                        <g stroke="#9898b8" strokeWidth="1" opacity="0.7">
                          <line x1="70" y1="295" x2="530" y2="295" />
                          <line x1="70" y1="290" x2="70" y2="300" />
                          <line x1="530" y1="290" x2="530" y2="300" />
                          <text x="300" y="310" fill="#e8ff47" fontSize="10" fontFamily="monospace" textAnchor="middle">
                            SPAN: {gridSpacing * 1500} mm &bull; ROTATION: {louverAngle}°
                          </text>
                        </g>
                      )}
                    </g>
                  )}

                  {activePreset.id === 'floorplan' && (
                    <g>
                      {/* Perimeter Building Footprint */}
                      <rect x="70" y="40" width="460" height="230" fill="none" stroke="#e8ff47" strokeWidth="2.5" />
                      
                      {/* Central Elevator / Service Core */}
                      <rect x="230" y="100" width="140" height="110" fill="rgba(255,107,53,0.15)" stroke="#ff6b35" strokeWidth="2" strokeDasharray="6 3" />
                      <line x1="230" y1="100" x2="370" y2="210" stroke="#ff6b35" strokeWidth="1" strokeOpacity="0.5" />
                      <line x1="230" y1="210" x2="370" y2="100" stroke="#ff6b35" strokeWidth="1" strokeOpacity="0.5" />
                      
                      {/* Structural Columns */}
                      {[70, 200, 400, 530].map((cx, i) =>
                        [40, 155, 270].map((cy, j) => (
                          <rect key={`${i}-${j}`} x={cx - 6} y={cy - 6} width="12" height="12" fill="#ffffff" stroke="#e8ff47" strokeWidth="1" />
                        ))
                      )}

                      {/* Office Zoning Divisions */}
                      <line x1="70" y1="155" x2="230" y2="155" stroke="rgba(255,255,255,0.4)" strokeWidth="1" strokeDasharray="4 4" />
                      <line x1="370" y1="155" x2="530" y2="155" stroke="rgba(255,255,255,0.4)" strokeWidth="1" strokeDasharray="4 4" />

                      {/* Annotations */}
                      <text x="300" y="160" fill="#ff6b35" fontSize="10" fontFamily="monospace" textAnchor="middle" fontWeight="bold">
                        ELEVATOR & MEP CORE
                      </text>
                      <text x="145" y="110" fill="#e8ff47" fontSize="9" fontFamily="monospace" textAnchor="middle">
                        ZONE A (OPEN CAD)
                      </text>
                      <text x="455" y="110" fill="#e8ff47" fontSize="9" fontFamily="monospace" textAnchor="middle">
                        ZONE B (BIM LAB)
                      </text>

                      {showDimensions && (
                        <g stroke="#9898b8" strokeWidth="1" opacity="0.8">
                          <text x="300" y="30" fill="#9898b8" fontSize="10" fontFamily="monospace" textAnchor="middle">
                            TOTAL BUILDING WIDTH: 33,600 mm
                          </text>
                        </g>
                      )}
                    </g>
                  )}

                  {activePreset.id === 'midjourney' && (
                    <g>
                      {/* Organic Parametric Roof Mesh Simulation */}
                      <path
                        d="M 60 220 Q 200 40 300 160 T 540 100 L 540 240 L 60 240 Z"
                        fill="rgba(232,255,71,0.08)"
                        stroke="#e8ff47"
                        strokeWidth="2"
                      />
                      {Array.from({ length: 18 }).map((_, i) => {
                        const px = 80 + i * 26;
                        return (
                          <line
                            key={i}
                            x1={px}
                            y1="240"
                            x2={px + 10}
                            y2={110 + Math.sin(i * 0.5) * 40}
                            stroke="#ff6b35"
                            strokeWidth="1.2"
                            strokeOpacity="0.7"
                          />
                        );
                      })}
                      <circle cx="280" cy="110" r="40" fill="none" stroke="#a78bfa" strokeWidth="1" strokeDasharray="4 4" />
                      <text x="300" y="270" fill="#e8ff47" fontSize="11" fontFamily="monospace" textAnchor="middle">
                        CONTROLNET CAD WIREFRAME SYNCHRONIZATION // CAMERA: 35mm f/8
                      </text>
                    </g>
                  )}

                  {activePreset.id === 'truss' && (
                    <g>
                      {/* Space-frame Arch Canopy */}
                      {Array.from({ length: 15 }).map((_, i) => {
                        const x = 70 + i * 32;
                        const archY = 220 - Math.sin((i / 14) * Math.PI) * 140;
                        const nextX = 70 + (i + 1) * 32;
                        const nextArchY = 220 - Math.sin(((i + 1) / 14) * Math.PI) * 140;
                        return (
                          <g key={i}>
                            {i < 14 && (
                              <>
                                <line x1={x} y1={archY} x2={nextX} y2={nextArchY} stroke="#e8ff47" strokeWidth="2" />
                                <line x1={x} y1={archY + 25} x2={nextX} y2={nextArchY + 25} stroke="#ff6b35" strokeWidth="1.5" />
                                <line x1={x} y1={archY} x2={nextX} y2={nextArchY + 25} stroke="rgba(255,255,255,0.4)" strokeWidth="1" />
                                <line x1={nextX} y1={nextArchY} x2={x} y2={archY + 25} stroke="rgba(255,255,255,0.4)" strokeWidth="1" />
                              </>
                            )}
                            <circle cx={x} cy={archY} r="3" fill="#ffffff" />
                            <circle cx={x} cy={archY + 25} r="2.5" fill="#e8ff47" />
                          </g>
                        );
                      })}
                      <text x="300" y="295" fill="#e8ff47" fontSize="10" fontFamily="monospace" textAnchor="middle">
                        60M CLEAR SPAN SPACE TRUSS &bull; CAST STEEL PIN NODES
                      </text>
                    </g>
                  )}
                </svg>

                {/* Snapping point hover effect indicator */}
                <div className="absolute bottom-3 right-3 text-[10px] font-mono text-mist-900 bg-ink-900/90 px-2.5 py-1 rounded border border-white/10">
                  Status: 2D/3D BIM Synced
                </div>
              </div>

              {/* Parametric Flex Sliders */}
              <div className="mt-4 pt-4 border-t border-white/5 space-y-3">
                <div className="flex items-center justify-between text-xs font-mono">
                  <span className="text-mist-700 flex items-center gap-1.5">
                    <Sliders size={13} className="text-signal" />
                    Louver Rotation / Facade Flex Angle:
                  </span>
                  <span className="text-signal font-bold">{louverAngle}°</span>
                </div>
                <input
                  type="range"
                  min="0"
                  max="90"
                  value={louverAngle}
                  onChange={(e) => setLouverAngle(parseInt(e.target.value, 10))}
                  className="w-full accent-signal bg-ink-800 h-1.5 rounded-lg appearance-none cursor-pointer"
                />

                <div className="flex items-center justify-between text-xs font-mono pt-1">
                  <span className="text-mist-700">Modular Grid Bay Count:</span>
                  <span className="text-signal font-bold">{gridSpacing} Bays</span>
                </div>
                <input
                  type="range"
                  min="6"
                  max="18"
                  value={gridSpacing}
                  onChange={(e) => setGridSpacing(parseInt(e.target.value, 10))}
                  className="w-full accent-signal bg-ink-800 h-1.5 rounded-lg appearance-none cursor-pointer"
                />
              </div>

            </div>
          </div>

        </div>

        {/* Free 1000 Users Callout Banner */}
        <div className="mt-12 p-6 sm:p-8 rounded-2xl bg-gradient-to-r from-ink-900 via-ink-850 to-ink-900 border border-signal/30 flex flex-col md:flex-row items-center justify-between gap-6">
          <div className="flex items-center gap-4">
            <div className="w-12 h-12 rounded-xl bg-signal/10 border border-signal/40 flex items-center justify-center text-signal">
              <Download size={24} />
            </div>
            <div>
              <h4 className="font-display text-lg sm:text-xl font-bold text-white">
                Download Full 500+ AutoCAD (.DWG) & Revit (.RFA) Master Library
              </h4>
              <p className="font-body text-sm text-mist-900">
                First 1,000 verified users get 100% free lifetime access. Must have an invitation or referral code to claim.
              </p>
            </div>
          </div>

          <button
            onClick={onOpenAccessModal}
            className="w-full md:w-auto bg-signal text-ink-950 font-display font-semibold px-8 py-3.5 rounded-full hover:bg-signal-dim transition-all shadow-lg shadow-signal/20 whitespace-nowrap"
          >
            Claim 1 of 1,000 Free Passes &rarr;
          </button>
        </div>

      </div>
    </section>
  );
}
